Corrected build test

diff --git a/.github/workflows/test-overlays.yaml b/.github/workflows/test-overlays.yaml
--- a/.github/workflows/test-overlays.yaml
+++ b/.github/workflows/test-overlays.yaml
@@ -24,8 +24,10 @@ jobs:
     - name: Find and build all overlays
       run: |
         find . -name overlays -type d | while read overlay_dir; do
-          if ! kustomize build "$overlay_dir"; then
-            echo "Kustomize build failed for $overlay_dir"
-            exit 1
-          fi
+          ls -1 $overlay_dir | while read overlay; do
+            if ! kustomize build $overlay_dir/$overlay > /dev/null; then
+              echo "Kustomize build failed for $overlay_dir/$overlay"
+              exit 1
+            fi
+          done
         done
